on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build
      - run: nix flake check
      - run: nix develop . --command true
      - run: nix develop .#amaranth --command true
      - run: nix develop .#yosys-amaranth --command true
